/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pinpoint.view;

import edu.pinpoint.database.DatabasePengajar;
import edu.pinpoint.error.PengajarException;
import edu.pinpoint.intity.Pengajar;
import edu.pinpoint.service.PengajarDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jemmy
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelSubmit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelReset = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(51, 254, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(17, 184, 144));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 254, 204));
        jLabel3.setText("Come Join Us");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 254, 204));
        jLabel6.setText("Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 40));

        txtNama.setBackground(new java.awt.Color(17, 187, 144));
        txtNama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(51, 254, 204));
        txtNama.setBorder(null);
        txtNama.setOpaque(false);
        jPanel3.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 254, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 254, 204));
        jLabel7.setText("NIP");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 40));

        txtEmail.setBackground(new java.awt.Color(17, 187, 144));
        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 254, 204));
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 180, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 254, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 254, 204));
        jLabel8.setText("Address");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 40));

        txtUsername.setBackground(new java.awt.Color(17, 187, 144));
        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 254, 204));
        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 254, 204));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 254, 204));
        jLabel9.setText("Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 40));

        jSeparator4.setBackground(new java.awt.Color(51, 254, 204));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 10));

        txtPass.setBackground(new java.awt.Color(17, 187, 144));
        txtPass.setForeground(new java.awt.Color(51, 254, 204));
        txtPass.setBorder(null);
        jPanel3.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 150, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 254, 204));
        jLabel10.setText("Username");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 40));

        txtAlamat.setBackground(new java.awt.Color(17, 187, 144));
        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(51, 254, 204));
        txtAlamat.setRows(5);
        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 254, 204)));
        jPanel3.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 254, 204));
        jLabel11.setText("Already Have An Account?");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 254, 204));
        jLabel12.setText("Click HERE");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        panelSubmit.setBackground(new java.awt.Color(17, 184, 144));
        panelSubmit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 254, 204)));
        panelSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubmitMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 254, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SUBMIT");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSubmitLayout = new javax.swing.GroupLayout(panelSubmit);
        panelSubmit.setLayout(panelSubmitLayout);
        panelSubmitLayout.setHorizontalGroup(
            panelSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        panelSubmitLayout.setVerticalGroup(
            panelSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        jPanel3.add(panelSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 20));

        panelReset.setBackground(new java.awt.Color(17, 184, 144));
        panelReset.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 254, 204)));
        panelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelResetMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 254, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("RESET");

        javax.swing.GroupLayout panelResetLayout = new javax.swing.GroupLayout(panelReset);
        panelReset.setLayout(panelResetLayout);
        panelResetLayout.setHorizontalGroup(
            panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        panelResetLayout.setVerticalGroup(
            panelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        jPanel3.add(panelReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 20));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 254, 204));
        jLabel16.setText("Email");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 40));

        txtNip.setBackground(new java.awt.Color(17, 187, 144));
        txtNip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNip.setForeground(new java.awt.Color(51, 254, 204));
        txtNip.setBorder(null);
        txtNip.setOpaque(false);
        jPanel3.add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 254, 204));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 390, 530));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/pinpoint/asset/PinpointLogo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 180));

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 187, 144));
        jLabel2.setText("Before We Expire");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 230, -1));

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 187, 144));
        jLabel5.setText("Aspire to Inspire");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, 100));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void panelSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubmitMouseClicked
        // TODO add your handling code here:
        
        Signup signup = new Signup();
        Login login = new Login();
        
        try {
            Pengajar pengajar = new Pengajar();
            PengajarDao pengajarDao = DatabasePengajar.getPengajarDao();
            String nip = txtNip.getText();
            String nama = txtNama.getText();
            String email = txtEmail.getText();
            String username = txtUsername.getText();
            String password = txtPass.getText();
            String alamat = txtAlamat.getText();
            
            
            
            if (nip.trim().equals("") || nama.trim().equals("")||email.trim().equals("")||username.trim().equals("")||password.trim().equals("")||alamat.trim().equals("")) {
                JOptionPane.showMessageDialog(signup,"Data Tidak Boleh Kosong");
            } else if (nip.length()>12) {
                JOptionPane.showMessageDialog(signup,"NIP Tidak Boleh Lebih Dari 12 Karakter");
            } else if (nama.length()>100) {
                JOptionPane.showMessageDialog(signup,"Nama Tidak Boleh Lebih Dari 100 Karakter");
            } else if (!email.contains("@") || !email.contains(".")) {
                JOptionPane.showMessageDialog(signup,"Email Anda Tidak Valid");
            } else if (email.length() > 100) {
                JOptionPane.showMessageDialog(signup,"Alamat Email Tidak Bisa Lebih Dari 100 Karakter");
            } else if (username.length() > 100) {
                JOptionPane.showMessageDialog(signup,"Username Tidak Boleh Lebih Dari 100 Karakter");
            } else if (password.length() > 100) {
                JOptionPane.showMessageDialog(signup,"Password Tidak Boleh Lebih Dari 100 Karater");
           }else if (alamat.length() > 255) {
                JOptionPane.showMessageDialog(signup,"Alamat Tidak Bisa Lebih Dari 255 Karakter");
            }
            else{
              
               pengajar.setNip(nip);
               pengajar.setNama(nama);
               pengajar.setEmail(email);
               pengajar.setUsername(username);
               pengajar.setPassword(password);
               pengajar.setAlamat(alamat);
            }
            
            pengajarDao.insertPengajar(pengajar);
            login.setVisible(true);
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(signup,"Tolong Periksa Kembali Data Yang Anda Isi");
          
           

        } catch (PengajarException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
   

    }//GEN-LAST:event_panelSubmitMouseClicked

    private void panelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelResetMouseClicked
        // TODO add your handling code here:
        txtNip.setText("");
        txtNama.setText("");
        txtEmail.setText("");
        txtUsername.setText("");
        txtPass.setText("");
        txtAlamat.setText("");
        
    }//GEN-LAST:event_panelResetMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panelReset;
    private javax.swing.JPanel panelSubmit;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
