/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pinpoint.view;

import edu.pinpoint.controller.JadwalController;
import edu.pinpoint.database.DatabasePengajar;
import edu.pinpoint.error.JadwalException;
import edu.pinpoint.event.JadwalListener;
import edu.pinpoint.intity.Jadwal;
import edu.pinpoint.model.JadwalModel;
import edu.pinpoint.model.TableJadwalModel;
import edu.pinpoint.service.JadwalDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Jemmy
 */
public class TambahJadwal extends javax.swing.JFrame{ //implements JadwalListener, ListSelectionListener{

    /**
     * Creates new form TambahJadwal
     
    private TableJadwalModel tableJadwalModel;
    
    private JadwalModel jadwalModel;

    private JadwalController jadwalController;
    
    private DetailMainMenuPengajar detailPengajar;
    
    private MainMenuSiswa menuSiswa = new MainMenuSiswa();*/
 
    public TambahJadwal() {
        /*this.detailPengajar = new DetailMainMenuPengajar();
      
       tableJadwalModel = new TableJadwalModel();
        
        jadwalModel = new JadwalModel();
        jadwalModel.setJadwalListener(this);
        
        jadwalController = new JadwalController();
        jadwalController.setJadwalModel(jadwalModel);*/
        
        initComponents();
        menu.setVisible(false);
        menu1.setVisible(false);
        txtMenu.setVisible(false);
        txtMenu1.setVisible(false);
        /*detailPengajar.getTblDetail().getSelectionModel().addListSelectionListener(this);
        detailPengajar.getTblDetail().setModel(tableJadwalModel);
        menuSiswa.getTblDetailSiswa().getSelectionModel().addListSelectionListener(this);
        menuSiswa.getTblDetailSiswa().setModel(tableJadwalModel);*/
        
 
        
    }

    public JTextField getTxtHari() {
        return txtHari;
    }

    public JTextField getTxtMatakuliah() {
        return txtMatakuliah;
    }

    public JTextField getTxtMulai() {
        return txtMulai;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNip() {
        return txtNip;
    }

    public JTextField getTxtRuang() {
        return txtRuang;
    }

    public JTextField getTxtUsai() {
        return txtUsai;
    }

    public JLabel getLblIdentifier() {
        return lblIdentifier;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtMenu = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        menuSebelum = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMenu1 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        menuSebelum1 = new javax.swing.JLabel();
        lblIdentifier = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatakuliah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRuang = new javax.swing.JTextField();
        txtHari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMulai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUsai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 184, 144));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 184, 144));
        jLabel5.setText("Schedule");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, -1));

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMenu.setBackground(new java.awt.Color(255, 255, 255));
        txtMenu.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        txtMenu.setForeground(new java.awt.Color(255, 255, 255));
        txtMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMenu.setText("Main Menu");
        txtMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(17, 184, 144)));
        txtMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                txtMenuAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(txtMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/pinpoint/asset/Menu2.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
        });
        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuSebelum.setBackground(new java.awt.Color(255, 255, 255));
        menuSebelum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        menuSebelum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuSebelum.setText("Main Menu");
        menuSebelum.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(17, 184, 144)));
        jPanel3.add(menuSebelum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 30));

        jPanel5.setBackground(new java.awt.Color(51, 255, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMenu1.setBackground(new java.awt.Color(255, 255, 255));
        txtMenu1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        txtMenu1.setForeground(new java.awt.Color(255, 255, 255));
        txtMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMenu1.setText("Logout");
        txtMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(17, 184, 144)));
        txtMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                txtMenu1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel5.add(txtMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/pinpoint/asset/Menu2.png"))); // NOI18N
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu1MouseEntered(evt);
            }
        });
        jPanel5.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuSebelum1.setBackground(new java.awt.Color(255, 255, 255));
        menuSebelum1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        menuSebelum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuSebelum1.setText("Logout");
        menuSebelum1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(17, 184, 144)));
        jPanel5.add(menuSebelum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, -1));

        lblIdentifier.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        lblIdentifier.setForeground(new java.awt.Color(17, 184, 144));
        lblIdentifier.setText("Add ");
        jPanel2.add(lblIdentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/pinpoint/asset/PinpointLogo2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATA KULIAH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 80, 20));

        txtMatakuliah.setBackground(new java.awt.Color(17, 184, 144));
        txtMatakuliah.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        txtMatakuliah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        jPanel1.add(txtMatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 200, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RUANGAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 70, 20));

        txtRuang.setBackground(new java.awt.Color(17, 184, 144));
        txtRuang.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtRuang.setForeground(new java.awt.Color(255, 255, 255));
        txtRuang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        jPanel1.add(txtRuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 200, 30));

        txtHari.setBackground(new java.awt.Color(17, 184, 144));
        txtHari.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtHari.setForeground(new java.awt.Color(255, 255, 255));
        txtHari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        jPanel1.add(txtHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 100, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("WAKTU MULAI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, 20));

        txtMulai.setBackground(new java.awt.Color(17, 184, 144));
        txtMulai.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtMulai.setForeground(new java.awt.Color(255, 255, 255));
        txtMulai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        txtMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMulaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 100, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HARI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NIP");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 30, 20));

        txtNip.setBackground(new java.awt.Color(17, 184, 144));
        txtNip.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtNip.setForeground(new java.awt.Color(255, 255, 255));
        txtNip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        jPanel1.add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NAMA PENGAJAR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 120, 20));

        txtNama.setBackground(new java.awt.Color(17, 184, 144));
        txtNama.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 200, 30));

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 340, 30));

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUBMIT");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 340, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("WAKTU USAI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 90, 20));

        txtUsai.setBackground(new java.awt.Color(17, 184, 144));
        txtUsai.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtUsai.setForeground(new java.awt.Color(255, 255, 255));
        txtUsai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 1, true));
        txtUsai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsai, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMulaiActionPerformed

    private void txtUsaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsaiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            TambahJadwal tambahJadwal = new TambahJadwal();
            Jadwal jadwal = new Jadwal();
            JadwalDao jadwalDao = DatabasePengajar.getJadwalDao();
            Statement statement = (Statement) DatabasePengajar.getConnection().createStatement();
            String SQLnip = "SELECT USERNAME FROM DATAPENGAJAR WHERE NIP='" + txtNip.getText() + "'";
            ResultSet result = statement.executeQuery(SQLnip);

            String nip = txtNip.getText() ;
            String nama = txtNama.getText();
            String matakuliah = txtMatakuliah.getText();
            String ruangan = txtRuang.getText();
            String hari = txtHari.getText();
            String mulai = txtMulai.getText();
            String usai = txtUsai.getText();

            if (result.next()) {
            } else {
                JOptionPane.showMessageDialog(tambahJadwal, "NIP Anda Salah");
            }

             if (nip.trim().equals("") || nama.trim().equals("") || matakuliah.trim().equals("") || ruangan.trim().equals("") || hari.trim().equals("") || mulai.trim().equals("") || usai.trim().equals("")) {
            JOptionPane.showMessageDialog(tambahJadwal,"Form Tidak Boleh Ada Yang Kosong");
        }else if (nip.length() > 12){
            JOptionPane.showMessageDialog(tambahJadwal, "NIP Tidak Boleh Lebih Dari 12 Digit");
        }else if (ruangan.length() > 10) {
            JOptionPane.showMessageDialog(tambahJadwal, "Nomor Ruangan Tidak Boleh Lebih Dari 10 Digit");
        }else if (!mulai.trim().contains(":") || !usai.trim().contains(":")) {
            JOptionPane.showMessageDialog(tambahJadwal, "Tolong Tulis Sesuai Contoh Yang Tersedia \n \n Contoh = 12:30 ");
        }else{

                jadwal.setNip(nip);
                jadwal.setNama(nama);
                jadwal.setMatakuliah(matakuliah);
                jadwal.setRuangan(ruangan);
                jadwal.setHari(hari);
                jadwal.setMulai(mulai);
                jadwal.setUsai(usai);

            }

            jadwalDao.insertJadwal(jadwal);
            JOptionPane.showMessageDialog(tambahJadwal, "Data Berhasil Di Tambahkan ");
            
            txtNip.setText("");
            txtNama.setText("");
            txtMatakuliah.setText("");
            txtRuang.setText("");
            txtHari.setText("");
            txtMulai.setText("");
            txtUsai.setText("");
           

            // this.setVisible(false);
            //JOptionPane.showMessageDialog(hm,"data berhasil si simpan");
        } catch (SQLException e) {

        } catch (JadwalException ex) {
            Logger.getLogger(TambahJadwal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:

        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtNip.setText("");
        txtNama.setText("");
        txtMatakuliah.setText("");
        txtMulai.setText("");
        txtUsai.setText("");
        txtHari.setText("");
        txtRuang.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        try {
            this.setVisible(false);
            DetailMainMenuPengajar detailPengajar = new DetailMainMenuPengajar();
            detailPengajar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TambahJadwal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void txtMenuAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtMenuAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenuAncestorMoved

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMouseEntered

    private void txtMenu1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtMenu1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenu1AncestorMoved

    private void menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1MouseEntered

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        menuSebelum.setVisible(false);
        menu.setVisible(true);
        txtMenu.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
         menuSebelum.setVisible(true);
        menu.setVisible(false);
        txtMenu.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        menuSebelum1.setVisible(false);
        menu1.setVisible(true);
        txtMenu1.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        menuSebelum1.setVisible(true);
        menu1.setVisible(false);
        txtMenu1.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblIdentifier;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menuSebelum;
    private javax.swing.JLabel menuSebelum1;
    private javax.swing.JTextField txtHari;
    private javax.swing.JTextField txtMatakuliah;
    private javax.swing.JLabel txtMenu;
    private javax.swing.JLabel txtMenu1;
    private javax.swing.JTextField txtMulai;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtRuang;
    private javax.swing.JTextField txtUsai;
    // End of variables declaration//GEN-END:variables
/*
    @Override
    public void onChange(JadwalModel jadwalModel) {
        txtNip.setText(jadwalModel.getNip()+"");
        txtNama.setText(jadwalModel.getNama());
        txtMatakuliah.setText(jadwalModel.getMatakuliah());
        txtRuang.setText(jadwalModel.getRuangan());
        txtMulai.setText(jadwalModel.getMulai());
        txtUsai.setText(jadwalModel.getUsai());
    }

    @Override
    public void onInsert(Jadwal jadwal) {
        tableJadwalModel.add(jadwal);
    }

    @Override
    public void onUpdate(Jadwal jadwal) {
        int index = detailPengajar.getTblDetail().getSelectedRow();
        tableJadwalModel.set(index, jadwal);
        int ind = menuSiswa.getTblDetailSiswa().getSelectedRow();
        tableJadwalModel.set(ind,jadwal);
        
    }

    @Override
    public void onDeleteJadwal() {
        
        int index = detailPengajar.getTblDetail().getSelectedRow();
        tableJadwalModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        try {
            Jadwal jadwal = tableJadwalModel.get(detailPengajar.getTblDetail().getSelectedRow());
            txtNip.setText(jadwalModel.getNip()+"");
            txtNama.setText(jadwalModel.getNama());
            txtMatakuliah.setText(jadwalModel.getMatakuliah());
            txtRuang.setText(jadwalModel.getRuangan());
            txtMulai.setText(jadwalModel.getMulai());
            txtUsai.setText(jadwalModel.getUsai());
        } catch (IndexOutOfBoundsException e) {
        }
    
    }
    public void loadDatabase() throws SQLException, JadwalException{
        JadwalDao jadwalDao = DatabasePengajar.getJadwalDao();
        tableJadwalModel.setList(jadwalDao.selectAllJadwal());
    }
    */
}
